import React from "react";

export type CodingPhase={id:string;goal:string;status?:string;dependencies?:string[];verify?:string[]};
export type CodingGraphTask={task_id:string;phase_id?:string;goal:string;depends_on?:string[];verification?:string[]};
export type CodingSubtaskProgress={task_id:string;phase_id:string;status:"WAITING"|"RUNNING"|"DONE"|"FAILED"|"PARTIAL";verification_status:"PASS"|"FAILED"|"NOT_RUN"|"UNVERIFIED";attempt:number;started_at?:number|null;finished_at?:number|null;failure_summary?:string|null};
export type CodingPhaseReport={id:string;phase_id:string;attempt:number;validation_status:string;structured_report?:{status?:string;errors?:string[];blockers?:string[];test_fail?:string[];build_executed?:string;build_pass?:string;manager_decision?:{decision?:string}}};
export type ImplementationPlanArtifact={target_root?:string;file_manifest?:{path?:string;action?:string}[];file_manifest_count?:number;scaffold_created_count?:number;scaffold_skipped_existing_count?:number;manifest_source?:string};
export type CodingTask={id:string;status:string;activity:string;plan_revision?:number;recovery_reason?:string;current_phase_id?:string|null;retry_count:number;max_retries:number;queue_position?:number|null;archived?:boolean;pause_requested?:boolean;execution_mode?:"NORMAL"|"HEAVY_BATCHED";batch_cursor?:number;batch_handoff?:{next_constraints?:string[];completed_phase_id?:string;next_phase_id?:string;changed_files?:string[];verification?:{phase_id?:string;status?:string;build_pass?:string;test_pass?:string[]}[]}|null;final_report?:{text?:string}|null;subtask_progress?:CodingSubtaskProgress[]|null;plan?:{phases?:CodingPhase[];tasks?:CodingGraphTask[];implementation_plan_artifact?:ImplementationPlanArtifact}|null;pending_authorization?:{requested_scope?:string[];reason?:string;unmet_criteria?:string[]}|null};

const active=new Set(["PLANNING","RUNNING","FINAL_REPORTING"]);
const pauseable=new Set(["QUEUED","PLANNING","RUNNING","FINAL_REPORTING"]);
const label:Record<string,string>={PLANNING:"計画を作成中",QWEN_PLAN_SCHEMA_REPAIR:"計画を修復中",QUEUED:"待機中",RUNNING:"実行中",FINAL_REPORTING:"最終結果を作成中",WAITING_FOR_PLAN_APPROVAL:"計画の承認待ち",WAITING_FOR_USER:"確認が必要です",RESUMABLE:"一時停止・再開可能",QWEN_REPLANNING:"再計画中",BLOCKED:"進行できません",COMPLETED:"完了"};
type DisplayState="WAITING"|"RUNNING"|"DONE"|"FAILED"|"PARTIAL"|"CHECKPOINT"|"UNKNOWN";
const displayLabels:Record<DisplayState,string>={WAITING:"WAITING",RUNNING:"RUNNING",DONE:"DONE",FAILED:"FAILED",PARTIAL:"PARTIAL",CHECKPOINT:"続行待ち",UNKNOWN:"状態を確認できません"};

export function taskIsActivelyRunning(task:CodingTask|null){return Boolean(task&&active.has(task.status))}
export function shouldAcceptPlanRevision(current:CodingTask|null,next:CodingTask){return !current||next.id!==current.id||(next.plan_revision||0)>=(current.plan_revision||0)}
function isCheckpoint(task:CodingTask){return task.status==="RESUMABLE"&&["RESOURCE_CHECKPOINT","IMPLEMENTATION_PREPARED"].includes(task.recovery_reason||"")&&!task.pending_authorization}
function displayState(task:CodingTask):DisplayState{if(task.status==="COMPLETED")return "DONE";if(task.status==="BLOCKED")return "FAILED";if(isCheckpoint(task))return "CHECKPOINT";if(task.status==="RESUMABLE")return "PARTIAL";if(["QUEUED","PLANNING","WAITING_FOR_PLAN_APPROVAL","WAITING_FOR_USER","QWEN_REPLANNING"].includes(task.status))return "WAITING";if(["RUNNING","FINAL_REPORTING"].includes(task.status))return "RUNNING";return "UNKNOWN"}
function latestReport(reports:CodingPhaseReport[],phaseId:string){return reports.filter(report=>report.phase_id===phaseId).at(-1)}
function verification(report:CodingPhaseReport|undefined):"PASS"|"FAILED"|"NOT_RUN"|"UNVERIFIED"{if(!report||report.validation_status!=="PASS")return "UNVERIFIED";const value=report.structured_report||{};if(value.status==="FAIL"||value.status==="BLOCKED"||(value.errors||[]).length||(value.blockers||[]).length||(value.test_fail||[]).length||value.build_pass==="FAIL")return "FAILED";if(value.status==="NOT_RUN"||value.build_executed==="NOT_RUN"||value.build_pass==="NOT_RUN")return "NOT_RUN";return value.manager_decision?.decision==="PASS"?"PASS":"UNVERIFIED"}
function failureSummary(report:CodingPhaseReport|undefined){const value=report?.structured_report;return value?.errors?.[0]||value?.blockers?.[0]||value?.test_fail?.[0]||""}

export function CodingTaskProgress({task,reports,loading,error,pausePending,onPause,onResume,onArchive}:{task:CodingTask;reports:CodingPhaseReport[];loading:boolean;error:string;pausePending:boolean;onPause:()=>void;onResume:()=>void;onArchive:()=>void}){
  const phases=task.plan?.phases||[],graph=task.plan?.tasks||[],subtasks=task.subtask_progress||[];
  const subtaskById=new Map(subtasks.map(item=>[item.task_id,item])),runningSubtask=subtasks.find(item=>item.status==="RUNNING");
  const explicitIndex=phases.findIndex(phase=>phase.id===task.current_phase_id),firstUnfinished=phases.findIndex(phase=>phase.status!=="pass");
  const index=explicitIndex>=0?explicitIndex:firstUnfinished>=0?firstUnfinished:Math.max(0,phases.length-1),current=phases[index],completed=subtasks.length?subtasks.filter(item=>item.status==="DONE").length:phases.filter(phase=>phase.status==="pass").length,state=displayState(task),statusKey=task.activity==="QWEN_PLAN_SCHEMA_REPAIR"?task.activity:task.status;
  const currentGraphTask=runningSubtask?graph.find(item=>item.task_id===runningSubtask.task_id):undefined;
  const finalText=task.final_report?.text?.trim();
  const checkpoint=isCheckpoint(task),handoff=task.batch_handoff;
  const finished=phases.find(phase=>phase.id===handoff?.completed_phase_id)||phases[(task.batch_cursor||1)-1];
  return <details className="coding-task-progress" open={taskIsActivelyRunning(task)||checkpoint}>
    <summary aria-label={`Coding Orchestrator: ${displayLabels[state]}`}><span><b>Coding Orchestrator</b><small>{subtasks.length?`${completed} / ${subtasks.length} tasks completed`:phases.length?`${completed} / ${phases.length} phases completed`:"Plan"}</small></span><span className={`coding-status state-${state.toLowerCase()}`}>{displayLabels[state]}</span>{!taskIsActivelyRunning(task)&&!task.archived&&<button type="button" className="coding-dismiss" aria-label="Dismiss Coding Orchestrator card" title="カードを消す" onClick={event=>{event.preventDefault();event.stopPropagation();onArchive()}}>×</button>}</summary>
    <div className="coding-task-details">
      <p className="coding-status-description" role="status">{label[statusKey]||"状態を確認中"}</p>{loading&&<p className="coding-loading" role="status">進行状況を更新中…</p>}{error&&<p className="coding-error" role="alert">進行状況を取得できませんでした。再試行できます。</p>}
      <p className="coding-plan-revision">Plan revision {task.plan_revision||0}</p>
      {(currentGraphTask||current)&&<section className="coding-current" aria-label="Current task"><small>Current task · {currentGraphTask?"Task Graph":`${Math.min(index+1,phases.length)} of ${phases.length}`}</small><strong>{currentGraphTask?.goal||current?.goal}</strong></section>}
      {checkpoint&&<section className="coding-batch-checkpoint" aria-label="継続チェックポイント"><p>{task.recovery_reason==="IMPLEMENTATION_PREPARED"?"計画と実装ファイルの準備が完了しました。続行すると次の工程を開始します。":"ここまで完了しました。続行すると次の工程を開始します。"}</p><p>完了した工程: {finished?.goal||"保存済みの工程"}</p><p>次の工程: {handoff?.next_constraints?.[0]||current?.goal||"保存済みの次工程"}</p><p>検証状態: {handoff?.verification?.at(-1)?.status||"記録を確認中"}</p>{handoff?.changed_files&&<p>変更ファイル数: {handoff.changed_files.length}</p>}{task.plan?.implementation_plan_artifact&&<p>実装マニフェスト: {task.plan.implementation_plan_artifact.file_manifest_count||0} ファイル / スキャフォールド作成 {task.plan.implementation_plan_artifact.scaffold_created_count||0}</p>}</section>}
      {task.current_phase_id&&<p>Correction {Math.min(task.retry_count,task.max_retries)} / {task.max_retries}</p>}{task.queue_position!=null&&<p>Queue position {task.queue_position}</p>}
      {task.pending_authorization&&<section className="coding-authorization" aria-label="Authorization required"><strong>Authorization required</strong><span>{task.pending_authorization.requested_scope?.length?task.pending_authorization.requested_scope.join(", "):task.pending_authorization.unmet_criteria?.join(" / ")||task.pending_authorization.reason||"追加の確認が必要です"}</span></section>}
      <section className="coding-phase-list" aria-label="Phase progress">{phases.map((phase,phaseIndex)=>{const report=latestReport(reports,phase.id),check=verification(report),isCurrent=phase.id===task.current_phase_id;return <details className={`coding-phase ${isCurrent?"current":""}`} key={phase.id} open={isCurrent}><summary><span aria-hidden="true">{phase.status==="pass"?"✓":isCurrent?"●":"○"}</span><span><b>Phase {phaseIndex+1}</b>{phase.goal}</span><small className={`verification-${check.toLowerCase()}`}>{check}</small></summary><div className="coding-phase-content">{phase.dependencies?.length?<p>Depends on: {phase.dependencies.join(", ")}</p>:null}{phase.verify?.length?<p>Verification: <strong className={`verification-${check.toLowerCase()}`}>{check}</strong></p>:null}{failureSummary(report)&&<p className="coding-failure">{failureSummary(report)}</p>}</div></details>})}</section>
      {graph.length>0&&<details className="coding-graph"><summary>Task Graph · {graph.length} tasks</summary><ol>{graph.map(item=>{const progress=subtaskById.get(item.task_id);return <li key={item.task_id}><b>{item.goal}</b>{progress&&<span className={`coding-subtask-state state-${progress.status.toLowerCase()}`}>{progress.status} · {progress.verification_status}</span>}{item.depends_on?.length?<small>Depends on: {item.depends_on.join(", ")}</small>:null}{item.verification?.length?<small>Verification: {item.verification.join(" / ")}</small>:null}{progress?.failure_summary&&<small className="coding-failure">{progress.failure_summary}</small>}</li>})}</ol>{!subtasks.length&&<p className="coding-graph-note">この既存 Plan には subtask 実行状態が保存されていないため、phase の persisted status を表示しています。</p>}</details>}
      {finalText&&<details className="coding-final-report" open><summary>Final result</summary><div>{finalText}</div></details>}
      <div className="coding-actions">{pauseable.has(task.status)&&!task.archived&&<button type="button" onClick={onPause} disabled={pausePending}>{pausePending?"一時停止を要求中…":"一時停止"}</button>}{task.status==="RESUMABLE"&&!task.archived&&<button type="button" onClick={onResume}>{checkpoint?"続行":"再開（リポジトリを再確認します）"}</button>}{!taskIsActivelyRunning(task)&&!task.archived&&<button type="button" onClick={onArchive}>アーカイブ</button>}</div>
    </div>
  </details>
}
