import React,{FormEvent,useEffect,useRef,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
import ReactMarkdown,{defaultUrlTransform} from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import "katex/dist/katex.min.css";
import {ChatComposer,Command,Attachment} from "./ChatComposer";
import {ProjectContext} from "./ProjectContext";
import {WebSettings} from "./WebSettings";
import {ExternalToolsSettings} from "./ExternalToolsSettings";
import {api,API,configureApi,hasSession,streamChat,cancelActiveStream} from "./api";
import {native,openExternal,pickPath} from "./native";
import {TableBlock,TableBlockView} from "./TableBlock";
type P={id:string;name:string;workspace_path?:string|null};type C={id:string;title:string};type AttachmentBlock={type:"attachment";name:string;mime_type?:string};type M={role:string;content:string;attachment?:{name:string;mimeType:string};blocks?:Array<TableBlock|AttachmentBlock>};type S=Record<string,any>;
function App(){const [commands,setCommands]=useState<Command[]>([]);const messagesRef=useRef<HTMLDivElement>(null);const[showJump,setShowJump]=useState(false);const [attachment,setAttachment]=useState<Attachment|null>(null);useEffect(()=>{if(API)void api("/commands").then(x=>setCommands(x.commands)).catch(()=>{})},[]);const[ps,setPs]=useState<P[]>([]),[p,setP]=useState<P|null>(null),[cs,setCs]=useState<C[]>([]),[c,setC]=useState<C|null>(null),[ms,setMs]=useState<M[]>([]),[core,setCore]=useState(""),[s,setS]=useState<S|null>(null),[text,setText]=useState(""),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[createOpen,setCreateOpen]=useState(false),[editingConversation,setEditingConversation]=useState<C|null>(null),[editingTitle,setEditingTitle]=useState(""),[editingProject,setEditingProject]=useState<P|null>(null),[editingProjectName,setEditingProjectName]=useState(""),[projectFilter,setProjectFilter]=useState(""),[err,setErr]=useState(""),[ready,setReady]=useState("STARTING");
const projects=async()=>{const x=await api("/projects");if(!Array.isArray(x.projects))throw Error("PROJECT_RESPONSE_SCHEMA_INVALID");console.debug("PROJECT_LIST_RESULT",{count:x.projects.length});setPs(x.projects);setP(old=>x.projects.find((q:P)=>q.id===old?.id)||x.projects[0]||null)};useEffect(()=>{const refresh=()=>{void projects().catch(()=>{})};window.addEventListener("focus",refresh);const timer=window.setInterval(refresh,3000);return()=>{window.removeEventListener("focus",refresh);window.clearInterval(timer)}},[]);useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape"){setOpen(false);setCreateOpen(false)}};window.addEventListener("keydown",onKey);(async()=>{try{console.debug("GUI_BOOTSTRAP_START");const invoke=(window as any).__TAURI__?.core?.invoke;console.debug(invoke?"TAURI_BRIDGE_AVAILABLE":"TAURI_BRIDGE_UNAVAILABLE");if(invoke){console.debug("BACKEND_CONFIG_REQUEST_START");const cfg=await invoke("backend_config");console.debug("BACKEND_CONFIG_REQUEST_SUCCESS",{API_URL_PRESENT:!!cfg?.api_url,SESSION_TOKEN_PRESENT:!!cfg?.session_token});if(!cfg?.api_url||!cfg?.session_token)throw Error("BACKEND_CONFIG_UNAVAILABLE");configureApi(cfg.api_url,cfg.session_token)}else if(!API)throw Error("BACKEND_CONFIG_UNAVAILABLE");await api("/health");setCommands((await api("/commands")).commands);setReady("READY");try{setS(await api("/settings"));await projects();console.debug("GUI_INITIAL_LOAD_PASS")}catch(e:any){setErr(e.message)}}catch(e:any){setReady("FAILED");setErr(e.message)}})();return()=>window.removeEventListener("keydown",onKey)},[]);useEffect(()=>{if(!p){setCs([]);setC(null);setMs([]);return}Promise.all([api(`/projects/${p.id}/conversations`),api(`/projects/${p.id}/core-context`)]).then(([x,y])=>{setCs(x.conversations);setC(null);setMs([]);setCore(y.content)}).catch(e=>setErr(e.message))},[p?.id]);useEffect(()=>{setAttachment(null)},[p?.id]);
const saveProjectName=async()=>{if(!editingProject)return;const name=editingProjectName.trim();if(!name){setEditingProject(null);return}try{const updated=await api(`/projects/${editingProject.id}`,{method:"PATCH",body:JSON.stringify({name})});setPs(xs=>xs.map(x=>x.id===updated.id?{...x,name:updated.name}:x));setP(x=>x&&x.id===updated.id?{...x,name:updated.name}:x)}catch(e:any){setErr(e?.message||String(e))}finally{setEditingProject(null)}};const select=async(x:C)=>{if(!p)return;try{const v=await api(`/projects/${p.id}/conversations/${x.id}`);setC(x);setMs(v.messages)}catch(e:any){setErr(`CONVERSATION_HISTORY_LOAD_FAILED: ${e.message}`)}};useEffect(()=>{if(!p||!c)return;const refresh=()=>{void api(`/projects/${p.id}/conversations/${c.id}`).then(v=>setMs(v.messages)).catch(()=>{})};const timer=window.setInterval(refresh,1500);return()=>window.clearInterval(timer)},[p?.id,c?.id]);const saveConversationTitle=async()=>{if(!p||!editingConversation)return;const title=editingTitle.trim();if(!title){setEditingConversation(null);return}try{const updated=await api(`/projects/${p.id}/conversations/${editingConversation.id}`,{method:"PATCH",body:JSON.stringify({title})});setCs(xs=>xs.map(x=>x.id===updated.id?{...x,title:updated.title}:x));setC(x=>x&&x.id===updated.id?{...x,title:updated.title}:x)}catch(e:any){setErr(e.message)}finally{setEditingConversation(null)}};const newConversation=async()=>{if(!p)return;try{const x=await api(`/projects/${p.id}/conversations`,{method:"POST"});setCs(old=>[x,...old]);setC({id:x.id,title:x.title});setMs([])}catch(e:any){setErr(`CONVERSATION_CREATE_FAILED: ${e.message}`)}};const remove=async(x:C)=>{try{await api(`/conversations/${x.id}`,{method:"DELETE"});setCs(old=>old.filter(q=>q.id!==x.id));if(c?.id===x.id){setC(null);setMs([])}}catch(e:any){setErr(e.message)}};const create=async(name:string,workspace:string)=>{try{const x=await api("/projects",{method:"POST",body:JSON.stringify({name,workspace_path:workspace||null})});await projects();setP(x);setCreateOpen(false)}catch(e:any){setErr(e.message)}};const assignWorkspace=async(project:P)=>{try{const selected=await pickPath(true);if(!selected)return;await api(`/projects/${project.id}`,{method:"PATCH",body:JSON.stringify({workspace_path:selected})});await projects()}catch(e:any){setErr(e?.message||String(e))}};const send=async(e:FormEvent)=>{e.preventDefault();const outgoingAttachment=attachment;if(!p||(!text.trim()&&!outgoingAttachment)||busy)return;const q=text.trim()||(outgoingAttachment?.mimeType.startsWith("image/")?"添付画像を確認してください。":"添付ファイルを確認してください。");
if(q.startsWith("/")){setBusy(true);setErr("");setMs(x=>[...x,{role:"user",content:q}]);try{const result=await api("/commands",{method:"POST",body:JSON.stringify({text:q,project_id:p.id,conversation_id:c?.id||null})});if(result.ui_action){const selected=await pickPath(result.ui_action==="workspace");if(selected){const pathCommand=result.ui_action==="workspace"?"/workspace set ":"/context load ";const loaded=await api("/commands",{method:"POST",body:JSON.stringify({text:pathCommand+JSON.stringify(selected),project_id:p.id,conversation_id:result.conversation_id||c?.id||null})});setMs(x=>[...x,{role:"assistant",content:loaded.message||JSON.stringify(loaded),blocks:Array.isArray(loaded.blocks)?loaded.blocks:undefined}]);setC({id:loaded.conversation_id||result.conversation_id,title:q.slice(0,120)});await projects()}}else {setMs(x=>[...x,{role:"assistant",content:result.message||JSON.stringify(result),blocks:Array.isArray(result.blocks)?result.blocks:undefined}]);if(result.conversation_id)setC({id:result.conversation_id,title:q.slice(0,120)});}window.dispatchEvent(new Event("olcr-command-complete"));setText("")}catch(e:any){setErr(e?.message||String(e))}finally{setBusy(false)}return}
// Structured/local tools must use the authoritative /api/chat path. The
// streaming endpoint is reserved for ordinary Brain prose; sending a known
// EONET/Federal Register/SymPy request there would bypass the terminal
// renderer and allow model-memory output to replace provider evidence.
const externalToolRequest=/(?:自然災害|山火事|火山|eonet|federal\s*register|連邦官報|米国官報|因数分解|記号計算|微分|積分|簡約|sympy|factor|differentiate|integrate|simplify)/i.test(q);
const planningShortChoice=/^(?:(?:全部|全て|すべて)(?:[ABC]|[1-9][0-9]*|おすすめ|お勧め|任せる|おまかせ)(?:で)?|[ABC]|[1-9][0-9]*|おすすめ|お勧め|任せる|おまかせ|(?:(?:Q?[0-9]+(?:と[0-9]+)*)\s*(?:=|は|:|：)\s*(?:[ABC]|[1-9][0-9]*)\s*[、,，]?\s*)+|最初(?:だけ)?\s*(?:[ABC]|[1-9][0-9]*)\s*[、,，]\s*(?:あとは|残りは)\s*(?:[ABC]|[1-9][0-9]*))$/i.test(q.trim());
const streamable=!outgoingAttachment&&!externalToolRequest&&!planningShortChoice&&!/(?:作成|作って|実装|修正|変更|追加|コーディング|coding task|ファイル|天気|気温|PM2\.5|大気|ニュース|news|検索|調べて|Wikidata|ISBN|PubChem|GDP|OECD|臨床試験|openFDA|日の出|日の入り|github|route|距離)/i.test(q);
setText("");setMs(x=>[...x,{role:"user",content:q,attachment:outgoingAttachment?{name:outgoingAttachment.name,mimeType:outgoingAttachment.mimeType}:undefined}]);setBusy(true);setErr("");
if(streamable){let assistantMessageIndex=-1;let streamError="";let streamConversationId=c?.id||"";try{await streamChat({message:q,conversation_id:c?.id||null,project_id:p.id},event=>{const chunk=event.text;if(event.conversation_id)streamConversationId=event.conversation_id;if(event.type==="chunk"&&chunk){setMs(old=>{const next=[...old];const current=assistantMessageIndex>=0?next[assistantMessageIndex]:undefined;if(current?.role==="assistant"){const content=current.content;next[assistantMessageIndex]={...current,content:chunk.startsWith(content)?chunk:content+chunk}}else{assistantMessageIndex=next.length;next.push({role:"assistant",content:chunk})}return next})}else if(event.type==="error")streamError=event.message||"STREAM_FAILED";else if((event.type==="done"||event.type==="cancelled")&&event.task&&streamConversationId){setC({id:streamConversationId,title:q.slice(0,120)})}});if(streamError)throw Error(streamError);setCs((await api(`/projects/${p.id}/conversations`)).conversations)}catch(error:any){if(assistantMessageIndex<0)setText(q);setErr(error?.message||String(error))}finally{setBusy(false)}return}
console.debug("GUI_CHAT_SUBMIT",{apiBase:API,endpoint:"/chat",projectPresent:!!p,conversationPresent:!!c,sessionPresent:hasSession()});try{const messageId=crypto.randomUUID();const result=await api("/chat",{method:"POST",body:JSON.stringify({message:q,message_id:messageId,conversation_id:c?.id||null,project_id:p.id,attachment:outgoingAttachment?.dataUrl?null:outgoingAttachment,image:outgoingAttachment?.dataUrl?{name:outgoingAttachment.name,mime_type:outgoingAttachment.mimeType,data_url:outgoingAttachment.dataUrl}:null})});setC({id:result.conversation_id,title:q.slice(0,120)});setMs(old=>[...old,{role:"assistant",content:result.response,blocks:Array.isArray(result.blocks)?result.blocks:undefined}]);setCs((await api(`/projects/${p.id}/conversations`)).conversations);setAttachment(null)}catch(e:any){setText(q);setErr(e.message)}finally{setBusy(false)}};const removeProject=async(project:P)=>{try{await api(`/projects/${project.id}`,{method:"PATCH",body:JSON.stringify({archived:true})});if(p?.id===project.id){setP(null);setC(null);setMs([])}await projects()}catch(e){setErr((e as any)?.message||String(e))}};const saveCore=()=>p&&api(`/projects/${p.id}/core-context`,{method:"PUT",body:JSON.stringify({content:core})}).catch(e=>setErr(e.message));const saveSettings=()=>s&&api("/settings",{method:"PUT",body:JSON.stringify(s)}).then(setS).catch(e=>setErr(e.message));
useEffect(()=>{const el=messagesRef.current;if(!el)return;const update=()=>setShowJump(el.scrollHeight-el.scrollTop-el.clientHeight>180);update();el.addEventListener("scroll",update,{passive:true});return()=>el.removeEventListener("scroll",update)},[ms.length]);
useEffect(()=>{if(!busy)return;const el=messagesRef.current;if(!el)return;el.scrollTop=el.scrollHeight},[ms,busy]);
const MESSAGE_URL_PATTERN=/(https?:\/\/[^\s<]+|file:\/\/\/[^\s<]+|\/(?:Users|private|tmp|var|Volumes)\/[^\s<]+)/g;
const stripUrlPunctuation=(value:string)=>{const match=value.match(/[.,!?;:)]$/);return match?{target:value.slice(0,-1),punctuation:match[0]}:{target:value,punctuation:""}};
function remarkLinkify(){
  return (tree:any)=>{
    const visit=(node:any)=>{
      if(!Array.isArray(node.children))return;
      const children:any[]=[];
      for(const child of node.children){
        if(child.type!=="text"){if(!["link","inlineCode","code","math","inlineMath","html"].includes(child.type))visit(child);children.push(child);continue}
        let last=0;
        for(const match of child.value.matchAll(MESSAGE_URL_PATTERN)){
          const index=match.index??0;
          if(index>last)children.push({type:"text",value:child.value.slice(last,index)});
          const {target,punctuation}=stripUrlPunctuation(match[0]);
          children.push({type:"link",url:target,children:[{type:"text",value:target}]});
          if(punctuation)children.push({type:"text",value:punctuation});
          last=index+match[0].length;
        }
        if(last<child.value.length)children.push({type:"text",value:child.value.slice(last)});
      }
      node.children=children;
    };
    visit(tree);
  };
}
const markdownComponents:any={
 a:({href,children,...props}:any)=><a {...props} className="message-link" href={href} target="_blank" rel="noopener noreferrer" onClick={e=>{e.preventDefault();if(!href)return;void openExternal(href).catch(()=>window.open(href,"_blank","noopener,noreferrer"))}}>{children}</a>,
 table:({children,...props}:any)=><div className="table-scroll" tabIndex={0}><table {...props} className="message-table">{children}</table></div>,
 pre:({children}:any)=><pre className="message-code">{children}</pre>,
 code:({className,children,...props}:any)=><code {...props} className={className}>{children}</code>,
};
const markdownUrlTransform=(url:string)=>/^(?:file:\/\/\/|\/(?:Users|private|tmp|var|Volumes)\/)/.test(url)?url:defaultUrlTransform(url);
// Some model responses have been observed to append a lone slash immediately
// after an otherwise complete fenced code block. Keep code contents byte-for-
// byte intact and remove only that unambiguous display artefact.
const normalizeMessageMarkdown=(value:string)=>value.replace(/(```[ \t]*)\/[ \t]*$/,"$1");
function MessageMarkdown({text,allowCollapse=true}:{text:string;allowCollapse?:boolean}){if(allowCollapse&&text.length>LONG_PROMPT_LIMIT)return <LongPrompt text={text}/>;return <ReactMarkdown remarkPlugins={[remarkGfm,remarkMath,remarkLinkify]} rehypePlugins={[rehypeKatex]} urlTransform={markdownUrlTransform} components={markdownComponents}>{normalizeMessageMarkdown(text)}</ReactMarkdown>}
const LONG_PROMPT_LIMIT=5000;
function LongPrompt({text}:{text:string}){const title=text.replace(/\s+/g," ").trim().slice(0,72);return <details className="long-prompt"><summary className="message-attachment" title={title}>{title}{text.length>72?"…":""}</summary><div className="long-prompt-content"><MessageMarkdown text={text} allowCollapse={false}/></div></details>}

return <div className={open?"shell settings-open":"shell"}>
  <aside className="side">
    <div className="brand"><strong>OLCR</strong><small>LOCAL COGNITIVE RUNTIME</small></div>
    {!open&&<><button className="primary" onClick={()=>setCreateOpen(true)}>＋ New project</button><input aria-label="Filter projects" placeholder="Filter projects" value={projectFilter} onChange={e=>setProjectFilter(e.target.value)} />
    <div className="label">PROJECTS</div><div className="conversations">{ps.filter(project=>project.name.toLowerCase().includes(projectFilter.toLowerCase())).map(project=><div className="project-row" key={project.id}>{editingProject?.id===project.id?<input className="item project-item project-edit-input" autoFocus value={editingProjectName} onChange={e=>setEditingProjectName(e.target.value)} onBlur={()=>void saveProjectName()} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void saveProjectName()}}}/>:<button className={p?.id===project.id?"item project-item active":"item project-item"} onClick={()=>{setP(project);setC(null)}} onDoubleClick={()=>{setEditingProject(project);setEditingProjectName(project.name)}}><span>{project.name}</span><small>{project.workspace_path||"No workspace"}</small></button>}{!project.workspace_path&&<button className="workspace-assign" aria-label="Assign workspace" title="Assign workspace" onClick={()=>void assignWorkspace(project)}>＋</button>}<button className="project-delete" aria-label={`Delete project ${project.name}`} onClick={()=>void removeProject(project)}>×</button></div>)}</div>
    <div className="chat-title"><div className="label">CONVERSATIONS</div><button aria-label="New conversation" onClick={()=>void newConversation()}>＋</button></div><div className="conversations">{cs.map(item=><div className="conversation-row" key={item.id}>{editingConversation?.id===item.id?<input autoFocus value={editingTitle} onChange={e=>setEditingTitle(e.target.value)} onBlur={()=>void saveConversationTitle()} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void saveConversationTitle()}}}/>:<button className={c?.id===item.id?"item active":"item"} onClick={()=>void select(item)} onDoubleClick={()=>{setEditingConversation(item);setEditingTitle(item.title)}}>{item.title}</button>}<button className="conversation-delete" aria-label={`Delete conversation ${item.title}`} onClick={()=>void remove(item)}>×</button></div>)}</div></>}
  </aside>
  <main>
    <header><div className="title-wrap"><small>{open?"SETTINGS":"PROJECT WORKSPACE"}</small><h1>{open?"Settings":p?.name||"Select a project"}</h1></div><div className="header-actions"><span className="ready">{ready}</span><button className={open?"settings-button open":"settings-button"} onClick={()=>setOpen(v=>!v)}>{open?"← Back":"⚙ Settings"}</button></div></header>
    {open?<div className="inspect open"><div className="panel-heading"><h2>Settings</h2><button type="button" className="settings-close" aria-label="Close settings" title="Close settings" onClick={()=>setOpen(false)}>×</button></div>{s&&<ExternalToolsSettings api={api} settings={s} save={async next=>{const saved=await api("/settings",{method:"PUT",body:JSON.stringify(next)});setS(saved);return saved}}/>}<WebSettings api={api}/></div>:<>
      {err&&<div className="error" role="alert">{err}</div>}
      {p&&<ProjectContext projectId={p.id} api={api}/>}<div className="messages" ref={messagesRef}>{ms.length?ms.map((m,i)=><article className={m.role} key={`${i}-${m.role}`}><b>{m.role==="user"?"USER":"ASSISTANT"}</b>{m.attachment&&<div className="message-attachment" title={m.attachment.name}>📎 {m.attachment.name}</div>}{m.blocks?.map((block,index)=>block.type==="table"?<TableBlockView block={block as TableBlock} key={`block-${index}`}/>:block.type==="attachment"?<div className="message-attachment" title={(block as AttachmentBlock).name} key={`block-${index}`}>📎 {(block as AttachmentBlock).name}</div>:null)}<div className="message-markdown"><MessageMarkdown text={m.content}/></div><button className="copy-message" aria-label="Copy message" onClick={()=>void navigator.clipboard?.writeText(m.content)}>▣</button></article>):<div className="empty"><h2>Ask OLCR anything</h2><p>Deterministic tools and retrieval run locally.</p></div>}{showJump&&<button className="jump-latest" aria-label="Jump to latest" onClick={()=>messagesRef.current?.scrollTo({top:messagesRef.current.scrollHeight,behavior:"smooth"})}>↓</button>}</div><ChatComposer text={text} setText={setText} disabled={ready!=="READY"} loading={busy} pause={()=>void cancelActiveStream()} send={send} commands={commands} attachment={attachment} setAttachment={setAttachment} conversationId={c?.id}/>
    </>}
    {createOpen&&<Dialog create={create} close={()=>setCreateOpen(false)}/>}</main>
  </div>;
}

function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><h2>{title}</h2>{children}</section>}function Row({n,v}:{n:string;v:string}){return <div className="row"><span>{n}</span><b>{v}</b></div>}function Dialog({create,close}:{create:(a:string,b:string)=>void;close:()=>void}){const[n,setN]=useState(""),[w,setW]=useState(""),[drag,setDrag]=useState(false);const drop=(e:React.DragEvent)=>{e.preventDefault();setDrag(false);const file=e.dataTransfer.files[0] as (File&{path?:string})|undefined;if(file)setW(file.path||file.webkitRelativePath||file.name)};useEffect(()=>{const pending=native()?.event.listen<{paths:string[]}>("tauri://drag-drop",event=>{if(event.payload.paths[0])setW(event.payload.paths[0])});return()=>{void pending?.then(unlisten=>unlisten())}},[]);return <div className="modal"><form onSubmit={e=>{e.preventDefault();create(n,w)}}><h2>Create project</h2><label>Project name<input value={n} required autoFocus onChange={e=>setN(e.target.value)}/></label><label>Workspace file or directory<div className={drag?"workspace-drop active":"workspace-drop"} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={drop}><span>Drop a file here to use its path</span><input value={w} placeholder="Or enter a path" onChange={e=>setW(e.target.value)}/></div></label><footer><button type="button" onClick={close}>Cancel</button><button className="primary">Create</button></footer></form></div>}createRoot(document.getElementById("root")!).render(<App/>);
